FPS = 90
WIDTH = 800
HEIGHT = 800
FPS = 90
PLAYER_SPEED = 1.5
PLAYER_HEALTH = 100
PLAYER_DASH_SPEED = 8
PLAYER_DASH_DURATION= 100
PLAYER_DASH_COOLDOWN = 3000
PLAYER_MIN_TENSION_DURATION = 400
PLAYER_MAX_TENSION_DURATION = 2000
ARROW_SPEED = 7
ARROW_DAMAGE = 10
ENEMY_SPEED = 0.7
ENEMY_HEALTH = 100
ENEMY_DETECTION_DISTANCE = 250
ENEMY_SPRITE_WIDTH = 30
ENEMY_SPRITE_HEIGHT = 30
NUM_ENEMIES = 5
SWORD_STRIKE_COOLDOWN = 1200
SWORD_TIME_SWING = 800
SWORD_TIME_STRIKE = 200
SWORD_STRIKE_DAMAGE = 20
SWORD_STRIKE_RADIUS = 50
SWORD_SPRITE_WIDTH = 35
SWORD_SPRITE_HEIGHT = 35
TILE_SIZE = 30
FLOOR = 0
WALL = 1
PLAYER_SPAWN = 2
ENEMY_SPAWN = 3
TILE_MAP = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFW",
    "WFPPFFFEFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFWFFW",
    "WFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFW",
    "WFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFW",
    "WFFFFFFFFFWFFFFFFFFFFFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFW",
    "WFFFFFFFFFWFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFWW",
    "WFFFWFFFFFFFFFFFFFFFFFFWFFFFFFFWWFFFFFFFFFFFFFFFFFFFFW",
    "WFFFFFFFFWFFFFFFFFFFFFFFFWFFFFWFFFFFWFFFFFFFFFFFFWFFFW",
    "WFFFFWFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFW",
    "WFFFFWFFFFEFFFWFWFFFFFFFWWFFFFFFFFFWFFFFFWFFFFFFFFFFFW",
    "WFFFFFWFFFFFFFWFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFWWFW",
    "WFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFWWWWFFFFFFFFFFFFFWFW",
    "WFFFFFWFFFWFFFFFFFWWFFFFFFFWWFFFFFFFFFFFFFWFWFFFFFWFFW",
    "WFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFW",
    "WFWWFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFW",
    "WFFFWFFFFFFWFFFFWFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFWFFFW",
    "WFFFFFFFWFFFFFFFFFFFFFFWFFFFFWFFFFFFFFFFFWFFFFFFFFFFFW",
    "WFFFFFFFFFFFFFFFFWFFFFFWFFFFEFFFWFFFFFFFFFFFWFFFWFFFFW",
    "WFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFWFFFFW",
    "WFFFFFFFWFFFFFFFFFFFFFFFWWFFFFFFFFFFFFFFFWFFWFFFFFFEFW",
    "WFFFFFFFFFFFFFFFFFFFFFWFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFW",
    "WFFFFFFFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFWFFFFFFFFFFFWFFFW",
    "WFFFFFFFWFFFFFFFFFFFFFFFWFFFFFFFWFFFFFFFFFFFFFFFFFFFWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]
MAP_WIDTH_TILES = len(TILE_MAP[0])
MAP_HEIGHT_TILES = len(TILE_MAP)
MAP_WIDTH_PX = MAP_WIDTH_TILES * TILE_SIZE
MAP_HEIGHT_PX = MAP_HEIGHT_TILES * TILE_SIZE